### ISSUE TITLE
error message TaskSwitching

### ISSUE THREAD

**Issue by abidi-wq** [TheKleinLab/TaskSwitching#1]
Hello,
I tried to run Taskswitching protocol and i I receive the following error (I managed to run the protocole two weeks ago, I don't know why it dosn't work now?):

OSError: exception: access violation reading 0x00000000001A52D0
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\k
libs\__main__.py", line 326, in run
    env.exp.show_logo()
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\k
libs\KLExperiment.py", line 338, in show_logo
    blit(logo, 5, P.screen_c)
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\k
libs\KLGraphics\__init__.py", line 103, in blit
    gl.glBegin(gl.GL_QUADS)
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\O
penGL\latebind.py", line 63, in __call__
    return self.wrapperFunction( self.baseFunction, *args, **named )
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\O
penGL\GL\exceptional.py", line 40, in glBegin
    return baseFunction( mode )
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\O
penGL\platform\baseplatform.py", line 415, in __call__
    return self( *args, **named )

Best regards,

**Comment by a-hurst** [comment]
Hey @abidi-wq, is this on the same machine as before? The closest thing I’ve seen to this error is running a task on a Windows 10 machine where the drivers for the Intel GPU (an HD3000) have broken OpenGL support for some reason. If that’s the case there’s a workaround, but last time you said you were running on Windows 7 so that might not be your issue.

**Comment by abidi-wq** [comment]
I m using the same machine (with Windows 7).  
I uninstalled python , reinstalled it, then redoing all steps again  and it worked.
Do you have please other solutions to my problem or do I have to redo everything each time?

thanks

**Comment by a-hurst** [comment]
Hey @abidi-wq, just realized I never got back to you on this. Have you had any further issues with weird crashes using the experiment? Looking at the error again it looks like a bug with PyOpenGL (or your graphics drivers) rather than anything the experiment is doing, but I can still try to advice if it's not stable.

**Comment by abidi-wq** [comment]
hello, thanks for you message. I reinstalled the protocol on windows 10 and it works fine.

**Comment by a-hurst** [comment]
Great, glad to hear it!
